<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProductsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title', 255)->nullable();
            $table->decimal('price', 11, 0)->nullable();
            $table->text('description')->nullable();
            $table->unsignedInteger('image_id')->nullable();
            $table->unsignedInteger('category_id')->nullable();



            $table->foreign('image_id', 'image_id')->references('id')->on('images')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('category_id', 'category_id')->references('id')->on('categories')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
}
